lib/zendesk_apps_support/assets/src.js.erb, lib/zendesk_apps_support/package.rb, spec/package_spec.rb
:koala:
This PR adds `noTemplate` and `singleInstall` app-level settings for `zat serve`. Ultimately, I'd like ZAM to serve `installed.js` with the `singleInstall` setting serialized to support identification of whether an app is single install for routing purposes.
- Jira link: https://zendesk.atlassian.net/browse/APPS-2169
- None
=> [APPS-2169] Allow routing based on app ID

lib/zendesk_apps_support/package.rb
Load the translations file requested, not always `en.json`. 
/cc @pdeuter @benhass @princemaple 
- Classic Change: https://github.com/zendesk/zendesk/pull/16964
- ZAT Change: https://github.com/zendesk/zendesk_apps_tools/pull/86
- Low. Use a new param if their, otherwise continue using "en" as before.
=> load the requested translations, not just english

lib/zendesk_apps_support/app_version.rb
:koala:
1.0 has been the [official current version](https://developer.zendesk.com/apps/docs/agent/version_changelog#version-history) since September 30th 2014.
/cc @zendesk/quokka @maximeprades @chucknado 
- Developers will no longer be able to update apps running on 0.5
=> Bump current version of the framework to 1.0

lib/zendesk_apps_support/validations/source.rb
`confirm` is a built in javascript function, it should be allowed within zendesk applications.
=> Add confirm to allowed global variables

lib/zendesk_apps_support/assets/src.js.erb, lib/zendesk_apps_support/package.rb, spec/app/manifest.json, spec/package_spec.rb
Added the same three properties to app.js to mimic zam correctly.
Installation name is the same as the app name. In ZAM these are different.
https://github.com/zendesk/zendesk_app_market/pull/1378
=> added version and app name for zas!

lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/source.rb
Editors don't understand the SASS syntax inside .css file, this patch allows to maintain a .scss file instead of the regular .css file supplied.
`zat package` support available under zendesk/zendesk_apps_tools#115 .
=> Allow having .scss file too

config/locales/en.yml, lib/zendesk_apps_support/app_requirement.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/validations/requirements_spec.rb
:bear:
Add `channel_integrations` type to requirements.
Add validation rules for at most one channel_integration, and require each to have a `manifest` field.
- Jira link: https://zendesk.atlassian.net/browse/APPS-2928
- None
=> [APPS-2928] add channel_integrations requirement type

lib/zendesk_apps_support/package.rb, spec/package_spec.rb
:v:
/cc @zendesk/vegemite @zendesk/wombat 
We have code elsewhere that assumes `locations['zendesk'].keys` always returns a valid array of locations. However if the locations key was missing, that code snippet returns `[nil]`.
https://zendesk.atlassian.net/browse/AF-346
* [low] errors creating / updating no-location apps (eg requirements only)
=> AF-346 handle when location key is not supplied at all, fix some rubocop warnings

lib/zendesk_apps_support/package.rb, spec/package_spec.rb
This is for us to be able to store the long_description and installation_instructions in the app's zipfile, rather than as a separate manual installation step.
- `market_translations!` is now renamed to `runtime_translations`, no longer mutates its input and is a private method since it is only useful as an input to `compile_js`.
- `translations_for` is now public so that it can be used instead of `market_translations!` when persisting translations into a database when apps are uploaded.
- [ medium ] translations stop working for new uploads
=> Refactor a method

Gemfile.lock, lib/zendesk_apps_support.rb, lib/zendesk_apps_support/app_version.rb, lib/zendesk_apps_support/manifest/no_override_hash.rb, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/stylesheet_compiler.rb, lib/zendesk_apps_support/validations/manifest.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/validations/requirements_spec.rb, zendesk_apps_support.gemspec
- Removed `json-stream`: had implemented parallel functionality in NoOverrideHash, since that gem was only used in validating requirements.json let's not force it to every ZAT user.
- Removed require statements from being run before dependencies were needed, especially `sass`
Performance comparison:
```
ruby -rzendesk_apps_support -e ''  0.33s user 0.12s system 98% cpu 0.454 total
ruby -rzendesk_apps_support -e ''  0.33s user 0.11s system 98% cpu 0.453 total
ruby -rzendesk_apps_support -e ''  0.33s user 0.11s system 98% cpu 0.447 total
ruby -rzendesk_apps_support -e ''  0.35s user 0.12s system 98% cpu 0.482 total
ruby -rzendesk_apps_support -e ''  0.34s user 0.11s system 98% cpu 0.458 total
ruby -rzendesk_apps_support -e ''  0.33s user 0.11s system 98% cpu 0.453 total
ruby …
```
=> remove a dependency, do not load SASS every time this gem is required

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/manifest.rb, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/marketplace.rb, spec/fixtures/iframe_app.js, spec/fixtures/iframe_only_app/manifest.json, spec/fixtures/legacy_app_en.js, spec/fixtures/legacy_app_nl.js, spec/fixtures/legacy_app_no_template.js, spec/fixtures/symlinks/manifest.json, spec/manifest_spec.rb, spec/validations/manifest_spec.rb, spec/validations/marketplace_spec.rb
:v:
Add experiments option to manifest available to ZAF
* JIRA: https://zendesk.atlassian.net/browse/AF-504
* low: breaks app serialization
=> Add experiments option to manifest available to ZAF

lib/zendesk_apps_support/assets/src.js.erb, lib/zendesk_apps_support/package.rb, spec/fixtures/iframe_app.js, spec/fixtures/legacy_app_en.js, spec/fixtures/legacy_app_nl.js, spec/fixtures/legacy_app_no_template.js, spec/package_spec.rb
:v:
We supply icons from ZAS now, so host products don't have to guess and have them hardcoded!
Also, way more flexible.
* JIRA:
=> Add icons to src.js so we don't have to guess in lotus!

lib/zendesk_apps_support/location.rb, lib/zendesk_apps_support/manifest.rb
Add the modal location so that we can store the URL to redirect for signing.
cc @zendesk/vegemite 
https://zendesk.atlassian.net/browse/AF-526
- [low] failing app uploads / updates
=> AF-526 modals don't work with signed URLs

lib/zendesk_apps_support/location.rb
cc @zendesk/wombat @zendesk/orchid 
Once we get https://github.com/zendesk/zendesk_console/pull/12267 merged back into lotus, we will want to be able to indicate the 'ticket_editor' location to test out the new editor app location.
Wombats: can we redeploy ZAS once this is reviewed?
=> Add location for editor apps

lib/zendesk_apps_support/package.rb
:v:
svgSprite in zendesk_console caches the svg icons. This is super annoying in ZAT mode, so we append the time in seconds to mitigate this.
* JIRA:
=> No cache the svgs in ZAT

lib/zendesk_apps_support/manifest.rb, spec/manifest_spec.rb
:v:
Ensure requirements only apps specify Support as their product. This is to pass validations that the app can be uploaded from within Support.
* JIRA: https://zendesk.atlassian.net/browse/APPS-3271
* low: breaks product-related validations / features
=> [APPS-3271] Ensure requirements only apps specify Support as their product

lib/zendesk_apps_support/validations/source.rb, spec/validations/source_spec.rb
Cleanup of some variables that are also allowed by telling JSHint to validate for the browser environment.
cc @zendesk/vegemite
- [medium] unexpected JSHint errors in v1 apps
=> dont double-declare constants

.rubocop.yml, config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/manifest.rb, lib/zendesk_apps_support/validations/manifest.rb, spec/fixtures/marketing_only_app/manifest.json, spec/manifest_spec.rb, spec/validations/manifest_spec.rb
:v:
Hard-codes support for Zendesk Support product for `marketingOnly` apps (similar to #150), and adds validation that a marketing only app must not be private.
For reference, the old PR is here if anyone wants it: https://github.com/zendesk/zendesk_apps_support/compare/master...adammw/products-for-no-location-apps-bak
* JIRA: https://zendesk.atlassian.net/browse/AF-425
* low: could break products for marketing only apps (which don't use ZAS until https://github.com/zendesk/zendesk_app_market/pull/2000 anyway)
=> [AF-425] Set products for no location apps

Gemfile.lock, zendesk_apps_support.gemspec
Updates sassc bumping libsass from v3.4.1 to v3.4.3: https://github.com/sass/libsass/releases
cc @zendesk/vegemite 
- crashes in v1 apps using the newCssCompiler experiment
=> bump sassc to v1.11.2, pulling in latest release of libsass

lib/zendesk_apps_support/app_requirement.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/validations/requirements_spec.rb
:v:
Add organization fields as a resource type in app requirements
* JIRA: Related to testing https://zendesk.atlassian.net/browse/AF-577
* [low] breaks validations for app requirements
=> Add organization fields as a resource type in app requirements

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/validations/manifest.rb, spec/validations/manifest_spec.rb
People ask us on a semi-regular basis why their app won't upload and they get a missing `manifest.json` error. Often the reason is they zipped up a folder with everything else inside it, so there's no manifest in the root of the zip. Later we can just support that, but for now let's automate the answer we give people by a useful error message.
cc @zendesk/vegemite 
- [low] failing app uploads
=> special error message for when the entire app is nested in a directory

lib/zendesk_apps_support/app_version.rb, lib/zendesk_apps_support/validations/manifest.rb
:v:
Add support for arrays of versions as well as `sunsetting` and `sunsetted` versions.
This can be used to display warnings in ZAT, such as when running [`zat update`](https://github.com/zendesk/zendesk_apps_tools/pull/190).
* JIRA: https://zendesk.atlassian.net/browse/AF-681
* [low] New methods being added
=> [AF-681] Add SUNSETTING and SUNSETTED

lib/zendesk_apps_support/app_version.rb, spec/app_version_spec.rb
@zendesk/wombat @zendesk/vegemite 
Adding a new validation method to be used in the zendesk_app_market.
Sunsetting will mean updates only and no new apps.
once this gem is bumped, I will update the app market and then write specs for it.
* JIRA: https://zendesk.atlassian.net/browse/APPS-3371
low - breaks app updates/create
=> [APPS-3371] Add a new validation method and distinguish create from update

lib/zendesk_apps_support/manifest.rb, spec/manifest_spec.rb
:bear:
Allow marketing only apps to have products and therefore be available for chat.
The products are read from the locations in the manifest and used even if there are no locations specified within the product hash.
If no products are specified it defaults to support to keep it backwards compatible.
* JIRA: https://zendesk.atlassian.net/browse/CACT-272
* [low] Breaks marketing only apps
=> [CACT-272] Allow marketing only apps in chat

README.md, config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/translations.rb, spec/bookmarks_app/translations/en.json, spec/fixtures/legacy_app_en.js, spec/fixtures/legacy_app_en_experimental_css.js, spec/fixtures/legacy_app_nl.js, spec/fixtures/legacy_app_no_template.js, spec/package_spec.rb, spec/translations/zh-cn.json, spec/translations/zh-cn_keyval.json, spec/validations/fixture/invalid_en-US.json, spec/validations/fixture/invalid_en.json, spec/validations/fixture/valid_en-US.json, spec/validations/fixture/valid_en.json, spec/validations/translations_spec.rb
:v:
Following on from recent changes that require short_description, long_description, and installation_instructions for marketplace apps, en.json is also required to have the app > name property.
```
app {
name: "This is now required"
}
```
ZAT validation uses ZAS. When running `zat validate` a message is now displayed when a required property is missing.
A [PR to bump ZAT's version of ZAS will be required](https://github.com/zendesk/zendesk_apps_tools/pull/198) once this is merged and tagged.
* JIRA: https://zendesk.atlassian.net/browse/AF-776
* [low] Apps validations will fail
=> [AF-776] Check for existence of app name in en.json

lib/zendesk_apps_support/validations/translations.rb
:bear:
Airbrake was being caused by unsafe hash check when `app` key was not present.
This change makes the check for `app=>name` happen safely.
https://zendesk.airbrake.io/projects/105401/groups/2017693197944987628?tab=overview
* [low] Doesn't validate presence of app name correctly
=> [CACT-314] Fix airbrake caused by unsafe hash check

config/locales/en.yml, lib/zendesk_apps_support/validations/requirements.rb, spec/fixtures/chat_only_manifest.json, spec/validations/requirements_spec.rb
Chat only apps should not be able to have requirements, since we can't do anything with them in Chat. This PR ensures they fail validation.
https://zendesk.atlassian.net/browse/CACT-284
Risks:
Low: valid apps are not valid
=> [CACT-284] Disallow requirements chat-only apps

lib/zendesk_apps_support/location.rb
Defining a new chat background app location. This location is supposed to be a UI less app location and hence is not orderable.
ZAT and ZAM will have to update the gem versions once this is merged and gem version is bumped.
@zendesk/vegemite @zendesk/wombat
=> Define new location for chat background

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml
I submitted a previous PR to validate that Chat only apps can't have requirements, but I only updated the error message in `en.yml`. Apparently the error Cactus gets comes from `zendesk_apps_support.yml`, which I didn't catch. This PR updates the other translation.
JIRA: https://zendesk.atlassian.net/browse/CACT-284
=> [CACT-284] Update the other place translations live in ZAS

lib/zendesk_apps_support/package.rb, spec/fixtures/legacy_app_en.js, spec/fixtures/legacy_app_en_experimental_css.js, spec/fixtures/legacy_app_nl.js, spec/fixtures/legacy_app_no_template.js, spec/package_spec.rb, spec/translations/zh-cn.json
:bear:
We would like to read app name from `en.json`.
Instead of removing `name` from translations file (e.g. `en.json`) for all locales, we should keep the app name for the default locale.
* JIRA: https://zendesk.atlassian.net/browse/APPS-3536
* [low] create translation for unwanted locales
=> [APPS-3536] Only remove name in [translation].json for non-default locale

lib/zendesk_apps_support/manifest.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/fixtures/invalid_location_manifest.json, spec/validations/manifest_spec.rb, spec/validations/requirements_spec.rb
:bear:
In the requirements validation a call has been added to `manifest.products`, however since this call happens during validation there's no guarantee that the locations are valid and this can error out.
I've replaced this call to use the `products_ignore_locations` method which only looks at the specified products without checking the locations and added some tests for when an array of support locations is used.
* [low] Requirements validation issues
=> Fix requirements validations when invalid locations

lib/zendesk_apps_support/validations/translations.rb, spec/validations/translations_spec.rb
We got an airbrake when (I assume) the translations file is an empty hash. This PR fixes it.
https://zendesk.atlassian.net/browse/APPS-3649
https://zendesk.airbrake.io/projects/105401/groups/2049874272888525109?tab=overview&attribute_id=-8115297495119076088&resolved=false
=> [APPS-3649] Fix undefined method keys airbrake

lib/zendesk_apps_support/manifest.rb, spec/manifest_spec.rb
Turns out if you specify a location that's just a string, and the string doesn't match a known location name in Support (e.g. "ticket_sidebar"), ZAS will break when it tries to figure out what your products are based on your locations. This PR makes ZAS ignore locations it can't make any sense of.
https://zendesk.airbrake.io/projects/105401/groups/2039767550069022343?tab=notice-detail
https://zendesk.atlassian.net/browse/APPS-3651
=> [APPS-3651] Stop zas choking on strings that aren't products

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/manifest.rb, spec/validations/manifest_spec.rb
@zendesk/wombat @zendesk/vegemite 
returns an error which is more user friendly. 
Prior to this you would see a `something went wrong message` due to an exception thrown at the worker level. 
This also reduces airbrakes.
* low - breaks manifest validation
=> [APPS-3602] Manifest validation.Return error instead of exploding

lib/zendesk_apps_support/validations/manifest.rb, lib/zendesk_apps_support/validations/translations.rb, spec/validations/translations_spec.rb
Product names (Support, Chat, etc) were not being capitalized in error messages. This PR fixes that issue.
JIRA: https://zendesk.atlassian.net/browse/APPS-3613
Med: breaks app validation
=> [APPS-3613] Fix product name capitalization

lib/zendesk_apps_support/validations/svg.rb, spec/validations/svg_spec.rb
:v: 🐨 
/cc @zendesk/vegemite @zendesk/wombat 
Points to an SVG path that actually exists for the ZAM worker to (re)write to.
* Slack: https://zendesk.slack.com/archives/C122US89L/p1509644506000190
* [low] safe SVGs are rewritten and don't display as initially intended
=> Fix path to SVG file for writing sanitised markup

lib/zendesk_apps_support/installation.rb
Adding a new attribute to the installations class, this is to be used in lotus to check if a particular app instance is collapsible or not.
Required for: https://github.com/zendesk/zendesk_app_market/pull/2888
@zendesk/vegemite
=> Add collapsible attribute to installations

lib/zendesk_apps_support/package.rb
Easy peasy, lemon skeasy PR for not error when we don't have translations in V2.
=> don't run translation code for non-v2 apps.

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/validations/translations.rb, spec/validations/fixture/invalid_pt-br.json, spec/validations/fixture/valid_pt-br.json, spec/validations/translations_spec.rb
🐻 
/cc @zendesk/vegemite @zendesk/wombat 
Adds a new validation to each translation file, asserting it has a `label` key on each node under `parameters` . See https://developer.zendesk.com/apps/docs/agent/i18n for example.
* JIRA: https://zendesk.atlassian.net/browse/CACT-354
* [low] breaks translation validation
=> [CACT-354] Validates translation file when parameters are included

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/validations/manifest.rb, spec/validations/manifest_spec.rb
If we have a setting we can't check the url for validity, because we don't know how the url is setup.
This will validate any url setting that has a `{{setting.`` in it.
```
url: "{{setting.url}}"
url: "http://{{setting.domain}}.my_server.com/iframe.html"
url: "/assets/{{setting.page}}.html"
```
=> Valid {{setting.}} url

lib/zendesk_apps_support/manifest.rb, spec/manifest_spec.rb
RubyGems v2.7 introduces a change to the `Gem::Version` class which throws an error if an instance is initialised with `nil`. 
https://github.com/rubygems/rubygems/blob/2.7/lib/rubygems/version.rb#L173
Requirements only apps cannot have a specified framework version and were previously having the `iframe_only?` method return `false` but with the latest version of RubyGems this throws an error.
=> Handle nil framework version

lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/translations.rb, spec/validations/fixture/name_only_en.json, spec/validations/translations_spec.rb
@zendesk/wombat 
Adds a new optional parameter to the validate method, in case you want to skip translations
The PR that skips assets validation is coming in `apps_approval` once this gets merged.
=> [Preview Apps] - skip marketplace translation validation for preview apps

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/app_requirement.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/validations/requirements_spec.rb
:v:
/cc @zendesk/vegemite @zendesk/i18n 	
1. Allows `custom_resources_schema` to be defined within `requirements.json`, and
1. Does some basic client-side validation to ensure that the schema contains only valid and all required keys for the custom resources `/private/jobs` endpoint.
* https://zendesk.atlassian.net/browse/AF-1050
* https://zendesk.atlassian.net/browse/AF-1049
* Low - just passes validation on a new resource type when defined in an app.
=> [AF-1050] [AF-1049] Permit and validate custom resource schemas defined in requirements.json

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/app_requirement.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/validations/requirements_spec.rb
Restores https://github.com/zendesk/zendesk_apps_support/pull/212 with syntax fixed for Ruby 2.1
=> Permit and validate custom resource schemas defined in requirements.json

lib/zendesk_apps_support/assets/installed.js.erb, spec/fixtures/installed_no_logging.js, spec/fixtures/installed_with_logging.js, spec/fixtures/installed_with_logging_rollbar.js
Making a shallow copy of window as window object can have references to other iframes, and the browser will not allow us deep copy an iframe from a different origin.
Error in browser without this fix:
@zendesk/vegemite
=> [AF-1128] [Patch] Make shallow copy of window instead of deep

Gemfile.lock, zendesk_apps_support.gemspec
A recent github security alerts report mentioned that loofah < 2.2.3 and nokogiri < 1.8.5 have known security vulnerabilities.  Therefore, per the recommendation of this report, bump loofah to 2.2.3 and nokogiri to 1.8.5.
* https://zendesk.atlassian.net/browse/AF-1509
* https://github.com/flavorjones/loofah/compare/v2.2.1...v2.2.3
* https://github.com/sparklemotion/nokogiri/compare/v1.8.1...v1.8.5
* (Medium) Breaks app validation in the apps_approval gem, which is used within Cactus (the app developer portal), thereby leading to problems with app submission
* (Low) Breaks app validations in the zendesk_apps_tools gem, thereby leading to issues with the zat command line tool
=> [AF-1509] Bump loofah and nokogiri to address security vulnerability

Gemfile.lock, lib/zendesk_apps_support/assets/installed.js.erb, lib/zendesk_apps_support/assets/src.js.erb, lib/zendesk_apps_support/installed.rb, lib/zendesk_apps_support/package.rb, spec/fixtures/iframe_app.js, spec/fixtures/installed.js, spec/fixtures/legacy_app_en.js, spec/fixtures/legacy_app_en_experimental_css.js, spec/fixtures/legacy_app_nl.js, spec/fixtures/legacy_app_no_template.js, spec/fixtures/multi_product_iframe_app.js, spec/installed_spec.rb, zendesk_apps_support.gemspec
After this being buggy for only 6 years, a fix.
Let's not use **name**, which is not unqiue (anymore), but let's use **id**.
Go by commit for very easy reviewing.
I had to limit `rb-inotify` to under `0.10.0` because Ruby 2.1 is not compatable with `0.10.0`.
=> No more name, use ID

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/validations/manifest.rb, spec/validations/manifest_spec.rb
✌️ @zendesk/vegemite
Remove validation that restricts `{{setting.yoursettingname}}` usage in signed urls.
* JIRA: https://zendesk.atlassian.net/browse/AF-1208
* [Low] removes validation only
=> Remove signed setting uri validation

Gemfile.lock, lib/zendesk_apps_support/assets/installed.js.erb, lib/zendesk_apps_support/assets/src.js.erb, lib/zendesk_apps_support/installed.rb, lib/zendesk_apps_support/package.rb, spec/fixtures/iframe_app.js, spec/fixtures/installed.js, spec/fixtures/legacy_app_en.js, spec/fixtures/legacy_app_en_experimental_css.js, spec/fixtures/legacy_app_nl.js, spec/fixtures/legacy_app_no_template.js, spec/fixtures/multi_product_iframe_app.js, spec/installed_spec.rb, zendesk_apps_support.gemspec
This reverts commit 97423193467f71a220bfc60a2fca9a064cc83c70, reversing
changes made to 90dbafcf1b8cb9b6fc5f4e14c1143c9b9021e2a8.
This change broke app serving in staging. Let's revert it while we investigate.
=> Revert "Merge pull request #218 from zendesk/olaf/no_name_but_id"

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml
@zendesk/dingo @zendesk/wattle-dev @zendesk/localization
Localization for [this](https://github.com/zendesk/zendesk_apps_support/pull/228).
<details>
<summary>app without unsupported mime type files</summary>
</details>
<details>
<summary>app with unsupported mime type files</summary>
</details>
- [JIRA](https://zendesk.atlassian.net/browse/MPORT-442)
- Low, strings only
=> [MPORT-442] Create Strings for MIME type ValidationError

Gemfile.lock, lib/zendesk_apps_support.rb, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/secrets.rb, spec/validations/secrets_spec.rb, zendesk_apps_support.gemspec
🐕 
Warn developers when the text files submitted in their app packages appear to contain secrets. Uses regexes from [the security checks PoC branch](https://github.com/zendesk/apps_approval/compare/fvilela/kari_security_work) to detect application specific secrets.
Currently these issues are caught as _warnings only_ and don't invalidate the app submission. 
<a href="https://cl.ly/37cea0ef143c" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/2B0l3w2k3L3r1X1q2S2L/Image%202019-05-16%20at%204.19.33%20pm.png" style="display: block;height: auto;width: 100%;"/></a>
* JIRA: https://zendesk.atlassian.net/browse/MPORT-445
* Translations: https://github.com/zendesk/zendesk_apps_support/pull/227
* Low - causes alarm/confusion with developers previously …
=> [MPORT-445] Warn when secrets are detected inside app text files

Gemfile.lock, config/locales/en.yml, lib/zendesk_apps_support.rb, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/requests.rb, spec/validations/requests_spec.rb, zendesk_apps_support.gemspec
🐕 
1. Scan JS and HTML files for common Javascript request function call patterns (i.e. jQuery, XMLHttpRequest, fetch, and Zendesk App Framework `.request` calls)
1. **Error** if calls are being made to:
1. RFC1918 **private** network addresses (10.0.0.0/8, 172.16.0.0/12, or 192.168.0.0/16 range)
1. RFC1122 **loopback** network addresses (127.0.0.0/8 range)
1. RFC3927 **link-local** network addresses (169.254.0.0/16 range)
1. **Warn** if requests are made via `http` instead of `https`.
Uses the [IPAddress gem](https://github.com/ipaddress-gem/ipaddress) to validate IPs and address types.
* JIRA: https://zendesk.atlassian.net/browse/MPORT-443
* Translations: https://github.com/zendesk/zendesk_apps_support/pull/231
* Medium - causes apps with legitimate requests to be …
=> [MPORT-443] Add validations for insecure and block-listed requests

lib/zendesk_apps_support/validations/requests.rb, spec/validations/mime_spec.rb, spec/validations/requests_spec.rb
@zendesk/dingo @zendesk/vegemite @zendesk/wattle 
This rewrite is necessary because of there are some edge cases that were not considered, which resulted in App uploads failing in production.
**The initial approach** includes **searching for Request Methods** and **evaluating these addresses**.
**Problems discovered:**  
1) Regex grabs everything after the request methods including `.then(..).catch(...)`. 
```
/api/v2/channels/voice/stats/current_queue_activity.json").then(function requestDone(data)
{cqa=data.current_queue_activity,resolve()})})}function getAgentActivity(){return
agents.online=0,agents.available=0,new Promise(function(resolve,reject)
{client.request("/api/v2/channels/voice/stats/agents_activity.json").then(
function requestDone(data)
...
...
URI(request.captures[0]) -> …
```
=> [MPORT-502] Rewrite Requests validation class

lib/zendesk_apps_support.rb, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/secure_settings.rb, lib/zendesk_apps_support/validations/source.rb, spec/validations/secure_settings_spec.rb, spec/validations/source_spec.rb
We are adding a new **validation warning (non-blocking) to suggest** using secure settings IF developers have token or passwords as a parameter.
**Steps:**
1) Look at manifest parameter names
2) If any of them has the word "token", "key", or "password" in them, display this message.
Link: https://developer.zendesk.com/apps/docs/developer-guide/using_sdk#using-secure-settings
3) Update other strings that are not related to this PR.
**Todos:**
- https://zendesk.atlassian.net/browse/MPORT-501
[low] Validation WARNING on secure settings doesn't work properly. 
[MPORT-501]: https://zendesk.atlassian.net/browse/MPORT-501
=> [MPORT-501] Include secure settings check in validations

lib/zendesk_apps_support/validations/requests.rb, spec/validations/requests_spec.rb
🐩
@zendesk/dingo @zendesk/vegemite
This rollbar alert showed up while I was QAing a card to validate for IP addresses. 
Currently, ZAM catches all ZAS ValidationErrors [here](https://github.com/zendesk/zendesk_app_market/blob/master/app/controllers/api/v2/app_validation_controller.rb#L22). The error message slipped past rescue and got bubbled up to [Rollbar]( https://rollbar-us.zendesk.com/Zendesk/App-Market/items/5324/). 
This is because in my [previous implementation](https://github.com/zendesk/zendesk_apps_support/pull/239), my warnings are treated as strings instead of ValidationError.
The approach here is to switch those `I18n.t(:msg)` methods into `ZendeskAppsSupport::Validations::ValidationError.new(:msg)`. I also updated the specs. 
Jira: …
=> [MPORT-502] Use ValidationError when validating IP addresses

lib/zendesk_apps_support/validations/secrets.rb, spec/validations/secrets_spec.rb
This PR adds a string to the secrets warning:
```
sgoedecke:private_app/ $ zat_dev validate                                                                                         [11:26:06]
warning  Possible secrets found in assets/foo.js ('password...'), assets/shared.js ('secret...'). Consider reviewing the contents of these files before submitting your app.
validate  OK
```
It also removes some keywords from the secret validation ('username' and 'pass') which I think are too liable to cause false positives. It's OK to have a username variable, and 'pass' is a substring of 'passed', which can come up a lot when writing code.
https://zendesk.atlassian.net/browse/MPORT-518
=> [MPORT-518] Give more information in secrets warnings

lib/zendesk_apps_support/location.rb
We'd like to be more specific when saying whether app is displayed on person or on company contact. 
This PR removed previous `contact_card` and adds `person_card` and `company_card`.
@Mehul-Porwal Is this kind of change safe? I assume there's 0 apps with previously defined IDs, so that shouldn't be a problem, right?
This PR also adds a new location `editor` - this is simmilar to `ticket_editor` location in Support. We already have a potential app ideas, and since I'm messing with locations I added it now :)
=> [SAF-853] Divided contact_card location to person_card and company_card

Gemfile.lock, README.md, zendesk_apps_support.gemspec
**Description:**
In the past, Gemfile.lock's `BUNDLE WITH` gets bumped by accident, mostly from gem deploy commands or rake bump commands. If this version goes above 2.0.0, our travis build will fail because we support stone-age ruby.
Jira: https://zendesk.atlassian.net/browse/MPORT-550
**Risk:** 
- Low: Developers can't bundle ZAS dependencies
=> [MPORT-550] Lockdown Bundler version

lib/zendesk_apps_support/validations/requests.rb, spec/validations/requests_spec.rb
cc: @zendesk/dingo @zendesk/wattle-dev  
[Private flag in app manifest is true by default. If a developer wishes to publish an app to the marketplace, this flag is set to false.](https://developer.zendesk.com/apps/docs/developer-guide/manifest#private)
In this implementation, when an app is private, these strings will show up as warnings instead. 
Jira: https://zendesk.atlassian.net/browse/MPORT-580
Risk: Low - App upload is blocked or fails
=> [MPORT-580] Change blockers to warnings for private apps IP requests

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml
We're limiting the number of custom object requirements for EAP to some yet to be determined number. We need a validation string for that (and for whatever the eventual GA limit will be).
https://drive.google.com/open?id=18yac8rV7kMe5qm49ERVFVCA7WOZl8vcP
=> [MPORT-600] Add string for too many custom object requirements

.rubocop.yml, lib/zendesk_apps_support/app_requirement.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/validations/requirements_spec.rb
Adds validation for custom object requirements, against this schema:
```
{
custom_objects: {
custom_object_types: [ { key: 'dog', schema: {...}} ],
custom_object_relationship_types: [ { key: 'dogs-join-cats', source: 'dog', target: 'cat' } ]
}
}
```
Output:
```
sgoedecke@-:~/Code/zendesk/zendesk_apps_tools|master⚡
⇒  bundle exec zat validate --path=/Users/sgoedecke/Desktop/apps/private_app_with_custom_object_types
validate  Missing required fields in requirements.json: "key" is required in "custom_object_types"
validate  Missing required fields in requirements.json: "schema" is required in "custom_object_types"
sgoedecke@-:~/Code/zendesk/zendesk_apps_tools|master⚡
⇒ bundle exec zat validate --path=/Users/sgoedecke/Desktop/apps/private_app_with_custom_object_types
validate …
```
=> [MPORT-600] Add validation for custom object types and relationships

lib/zendesk_apps_support/app_requirement.rb, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/package_spec.rb, spec/validations/requirements_spec.rb
After some discussion with @seangoedecke [here](https://github.com/zendesk/zendesk_app_market/pull/3854#discussion_r352382213) and offline, we decided the best place to put a method to check for custom object requirements is in zas. This adds it, and replaces some hard coded strings with consts.
=> [DINGO-651] Add custom_object_requirements helper method

lib/zendesk_apps_support/manifest/parameter.rb, lib/zendesk_apps_support/validations/manifest.rb, spec/validations/manifest_spec.rb
We are starting a new project `ZIS-ZAM-ZAP`, we have created a new kind called `oauth` during this process.
I've added this new kind to existed parameters and added validations to ensure there are only one this kind for manifest.
=> [APPS-4892]Add a new kind to parameter and add validation for manifest

.travis.yml, lib/zendesk_apps_support/location.rb, lib/zendesk_apps_support/package.rb, spec/package_spec.rb
This change adds `top_bar` location for Sell product. Together with location itself it also adds possibility to set icons for that location (i.e. to change the icon upon a notification).
The changes in the code are straightforward and in-line with what has been already there for Support product.
The tests for icon location have been refactored a bit to have a clearer way of mocking manifest locations differently for different scenarios.
JIRA issues: SELCHA-14, SELCHA-9
cc @zendesk/vegemite 
@zendesk/dingo
=> Add top_bar location for Zendesk Sell

lib/zendesk_apps_support/package.rb
We need to be able to call the `location_icons` method from within ZAM, and don't want to rely on it always working via a semi-hacky `send` call.
=> Make `location_icons` a public method

config/locales/translations/zendesk_apps_support.yml
/cc @zendesk/wattle @zendesk/dingo @zendesk/localization 
Add translation for when the parameter type is oauth and it is set to secure. 
* [RUNTIME] No
* [LOW] Adding translation
=> [APPS-5183]Add translation

lib/zendesk_apps_support/validations/manifest.rb, spec/validations/manifest_spec.rb
💐
Add validation for manifest for parameter type oauth. This cannot be seucre.
https://zendesk.atlassian.net/browse/APPS-5183
* [RUNTIME] No
* [Low] Adding validation
=> [APPS-5183]Add validation

config/locales/en.yml, lib/zendesk_apps_support/validations/manifest.rb, spec/validations/manifest_spec.rb
cc @zendesk/wattle 
Makes the oauth param required when the oauth section is present.
=> [APPS-4953] Make parameter with kind oauth required when oauth section is present

.travis.yml
🐕
Drop support for ruby 2.1 and 2.2, in preparation for merging the dependabot PR which bumps nokogiri to a more secure version.  Note though that bumping nokogiri requires that we drop 2.1 and 2.2, hence this change.
More context: A customer has asked for us to bump nokogiri per said dependabot change in order to address a security concern they have: https://support.zendesk.com/agent/tickets/5609005
Adds support for ruby 2.5 and ruby 2.6.
* See [this slack thread](https://zendesk.slack.com/archives/C1230V1CG/p1594681052320700) and this dependabot PR: https://github.com/zendesk/zendesk_apps_support/pull/259 .
* [Zendesk Support ticket regarding nokogiri security issue and need to bump said dependency](https://support.zendesk.com/agent/tickets/5609005)
* …
=> [VEGEMITE-312] The (old) ruby is deprecated, long live the new ruby

Gemfile.lock, lib/zendesk_apps_support/sass_functions.rb, zendesk_apps_support.gemspec
💐
As a part of upgrading rails 5.2.0, we have some gem dependency conflicts.
To resolve this, we need to update sassc to 2.0
```Bundler could not find compatible versions for gem "sassc":
In Gemfile:
administrate (~> 0.14.0) was resolved to 0.14.0, which depends on
sassc-rails (~> 2.1) was resolved to 2.1.2, which depends on
sassc (>= 2.0)
zendesk_apps_support (>= 4.29.4) was resolved to 4.29.5, which depends on
sassc (~> 1.11.2)
```
https://zendesk.atlassian.net/browse/APPS-5335
* [RUNTIME] No
* [Medium] Sassc gem bump
=> [APPS-5335]Update sassc

Gemfile.lock, zendesk_apps_support.gemspec
🐕
We accidentally switched to the latest Bundler when bumping gems. This rolls this back.
None.
=> Switch back to 1.17.3

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml
🐕
Adds strings for new warning about default settings for secure/hidden params.
@zendesk/localization
https://zendesk.atlassian.net/browse/DINGO-1372
* None: just a string
=> [DINGO-1372] Add strings for new warning validation

Gemfile.lock, lib/zendesk_apps_support/validations/mime.rb, lib/zendesk_apps_support/validations/secure_settings.rb, spec/validations/secure_settings_spec.rb, zendesk_apps_support.gemspec
🐕
This PR adds a new validation for default parameter values - if the param is hidden or secure, we warn the developer that they shouldn't store secrets in the defaults.
We can't use `Marcel::Magic` without defacto pinning `marcel` to v1+, so we need to do the `split('/')` logic ourselves.
https://zendesk.atlassian.net/browse/DINGO-1372
* Low: apps fail to upload
=> [DINGO-1372] Add warning for sensitive data in hidden fields

Gemfile.lock, zendesk_apps_support.gemspec
🐕
* Bumps the version of the gem so that we can use the new shiny validation for "flexible": true.
* Bumps bundler to a modern shiny version.
[VEG-599](https://zendesk.atlassian.net/browse/VEG-599)
* [RUNTIME] Can this change affect apps rendering for a user? No, version bump only.
* [Low] Change to bundler version might break other gems and systems that use this.
=> [VEG-599] Bump the version of the gem. Bump bundler to 2.2.26

lib/zendesk_apps_support/validations/requirements.rb
🐕
The requirements validation class expects all requirements to have a 'title' except custom objects/channel integrations, which are being excluded. Similarly, webhooks[ don't have a title attribute](https://developer.zendesk.com/api-reference/event-connectors/webhooks/webhooks/) so we need to exclude them from this validation.
Jira: https://zendesk.atlassian.net/browse/DINGO-1662
* [low] What features does this touch? Webhooks are incorrectly excluded from validation
=> [DINGO-1662] Exclude webhooks from title requirements

lib/zendesk_apps_support/app_requirement.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/validations/requirements_spec.rb
🐕
Adds required key validations for webhooks. This is mostly based on what is currently done for custom object key validation.
https://zendesk.atlassian.net/browse/DINGO-1662
* [low] Incorrectly validates webhooks, causing app validation to fail.
=> [DINGO-1662] Add validation for webhook keys

Gemfile.lock, zendesk_apps_support.gemspec
🐕
Bumps version to include https://github.com/zendesk/zendesk_apps_support/pull/319.
https://zendesk.atlassian.net/browse/DINGO-1662
* [low] Webhook validation is incorrect for apps
=> [DINGO-1662] Bump version from 4.30.1 to 4.31.0

lib/zendesk_apps_support/validations/requirements.rb, spec/validations/requirements_spec.rb
🐕
My [previous PR](https://github.com/zendesk/zendesk_apps_support/pull/319) added required key validation to webhook requirements in the following format:
```
{
webhooks: {
name: 'my webhook',
endpoint: 'https://foo.com/bar',
...etc
}
}
```
However we expect user to provide webhooks in the following structure:
```
{
webhooks: {
my_webhook_identifier: {
name: 'my webhook',
endpoint: 'https://foo.com/bar',
...etc
}
}
}
```
This updates the validation to handle the correct format, and adds an extra test for when multiple webhooks are specified.
https://zendesk.atlassian.net/browse/DINGO-1662
* [low] Webhook validation is broken in some other way
=> [DINGO-1662] Handle correct webhook requirement structure

Gemfile.lock, zendesk_apps_support.gemspec
🐕
Bugfix from the previous version, see https://github.com/zendesk/zendesk_apps_support/pull/321 for details.
https://zendesk.atlassian.net/browse/DINGO-1662
* [low] webhooks validation continues to be broken
=> [DINGO-1662] Bump version to v4.31.1

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/validations/manifest.rb, spec/validations/manifest_spec.rb
🐕
A private app (and potentially any marketplace app) can contain JavaScript in the manifest.json file which gets executed from the {subdomain}.zendesk.com domain.
STEPS TO REPRODUCE
1. Update the url field in an app in the manifest.json file to "url": "javascript:alert(document.domain)"
2. Package the app and Upload the private App to your account.
3. One the app is installed, click on the App and as the url field is populated, you will see an option to click on the "developer website" link.
4. Click on the link and the javascript will trigger the alert within the context of the accounts subdomain.
An attacker can use this vulnerability to construct a request that, if issued by another application user, will cause JavaScript code supplied by the attacker to execute …
=> [DINGO-1723] Add url validation

lib/zendesk_apps_support/assets/installed.js.erb, lib/zendesk_apps_support/installed.rb, spec/fixtures/installed.js, spec/installed_spec.rb
Rollbar integration has been shutdown, so this became dead code.
🐕
* [low] What features does this touch? `installed.js` rendering. Dead code removal.
=> [APPS-5975] Remove rollbarAccessToken when rendering installed.js

lib/zendesk_apps_support/installation.rb
🐕
Expose stripe subscription id
relate to [PR](https://github.com/zendesk/zendesk_app_market/pull/4981/files#diff-3c4c280a3fd5aba7847463db00c2b01037ed94ca2027a95243f1f7b3daaa8df1R26)
https://zendesk.atlassian.net/browse/DINGO-1836
* [low] Adding extra field
=> [DINGO-1836] Expose stripe subscription id

.github/workflows/ruby-gem-publication.yml
🐕
Ownership for zendesk_apps_support on rubygems.org is being removed ([thread](https://zendesk.slack.com/archives/C2BAXN0JH/p1658113415923469))
We onboard the Ruby Gems Workflow by following [Ruby Gems Workflow Onboarding](https://zendesk.atlassian.net/wiki/spaces/BRE/pages/5443454171/Ruby+Gems+Workflow+Onboarding)
This PR creates `.github/workflows/ruby-gem-publication.yml` according to https://github.com/zendesk/gw/blob/main/ruby-gem-publication/README.md
https://zendesk.slack.com/archives/C2BAXN0JH/p1658113415923469
* [low] fail to publish gem
=> Onboards to Ruby Gems Workflow

lib/zendesk_apps_support/validations/requirements.rb, spec/validations/requirements_spec.rb
💐
Prevents creating apps with http targets (which are now deprecated). We've already disabled the type `http_target` in https://github.com/zendesk/zendesk_apps_support/pull/325, but `url_target_v2` was missed.
https://zendesk.atlassian.net/browse/APPS-6222
* [low] Breaks apps validation
=> Disable url target v2 target type

Gemfile.lock, lib/zendesk_apps_support/app_version.rb, spec/app_version_spec.rb, spec/package_spec.rb, spec/validations/manifest_spec.rb, zendesk_apps_support.gemspec
💐
Removes support for deprecated app framework versions.
https://zendesk.atlassian.net/browse/APPS-6494
* [RUNTIME] Can this change affect apps rendering for a user? No, apps with deprecated versions are not being rendered.
* [low] What features does this touch? App framework version check
=> [APPS-6494] Remove deprecated framework versions

.github/workflows/actions.yml, Gemfile.lock, zendesk_apps_support.gemspec
[1] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
[2] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This prevents jobs in the matrix from uploading their cache archives
using the same key, while trying to share the archives where possible.
Also replaces deprecated flag --path=xxx with bundle config.
https://zendesk.atlassian.net/browse/VEG-1714
* [RUNTIME] Can this change affect apps rendering for a user?: No
* [Low] What features does this touch?: Manifest validation (last PR #352)
=> Bump version to 4.38.2; GHA chores

.github/workflows/actions.yml, .github/workflows/ruby-gem-publication.yml, Gemfile.lock, lib/zendesk_apps_support/validations/svg.rb, zendesk_apps_support.gemspec
[1] https://github.com/flavorjones/loofah/commit/7cda1210a99721b4fa6fc0f659ac75f00bec6b11
N/A
* [RUNTIME] Can this change affect apps rendering for a user? No, it's
used to validate SVG files.
* [Low] What features does this touch? SVG validation. `SafeList` is an
alias of the old constant.
=> Silent loofah deprecation warning; GHA touch-ups; bump version

Gemfile.lock, zendesk_apps_support.gemspec
💐
Makes the loofah dependency requirement looser to unblock the ZBT team. I tested this with ZAT and confirmed unit tests all still pass.
See https://zendesk.slack.com/archives/C1230V1CG/p1704180155370169 for context.
> Hello Team Vegemite :wave: In our framework (ZBT) we are using [zendesk_apps_support](https://github.com/zendesk/zendesk_apps_support), and we are unable to bump rack to address the vulnerability reported by Snyk because of unresolved dependencies. [zendesk_apps_support](https://github.com/zendesk/zendesk_apps_support) requires loofah to be >= 2.3.1', '< 2.20.0, but in ZBT we must bump loofah to 2.22.0 in order to allow us to upgrade rack.
Would you be able to loosen the version restriction so that we can perform the gem upgrade for our framework? …
=> Loosen loofah version restriction

config/locales/en.yml, config/locales/translations/zendesk_apps_support.yml, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/manifest.rb, spec/package_spec.rb, spec/validations/manifest_spec.rb
Description
Add manifest validation to disallow password type params.
The check is based on enabling _password_parameter_check to ensure this validation works only for new app submission. The value will be passed in from Apps approval and ZAM.
The apply _password_parameter_check value will be passed in from Apps Approval gem [here](https://github.com/zendesk/apps_approval/blob/main/lib/apps_approval/app_validation.rb#L21).
References
https://zendesk.atlassian.net/browse/APPS-6946
Risks
[RUNTIME] No
[low] Only adds an extra validation in manifest that works dependant on skip_password_parameter_check. Manifest validation can fail for apps.
=> [APPS-6946] Add manifest validation to deprecate password type param

config/locales/translations/zendesk_apps_support.yml
💐
Adds the messaging for the warning that password parameters will be deprecated and should no longer be used.
[Link to a JIRA or GitHub issue here if relevant](https://zendesk.atlassian.net/browse/APPS-7218)
* [None] String addition for translation
=> Add password parameter deprecation message

config/locales/en.yml, lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/manifest.rb, spec/package_spec.rb, spec/validations/manifest_spec.rb
💐
Shows a warning when a parameter of type password is being used.
[Link to a JIRA or GitHub issue here if relevant](https://zendesk.atlassian.net/browse/APPS-7218)
* [low] Incorrect validations
=> [APPS-7218] Add warning for password parameter

.github/workflows/actions.yml, .github/workflows/publish.yml, README.md, lib/zendesk_apps_support/version.rb, zendesk_apps_support.gemspec
Switches to [a Trusted Publishing workflow](https://guides.rubygems.org/trusted-publishing/).
This workflow will run whenever `version.rb` is changed in the `main` branch.
Setting `ENV["gem_push"]` is also not necessary anymore.
This workflow relies on the main branch being named `main`. Please rename it (`main` is the standard name across Zendesk).
`bundler-cache` for `setup-ruby` is set to false to prevent [cache poisoning attacks](https://adnanthekhan.com/2024/05/06/the-monsters-in-your-build-cache-github-actions-cache-poisoning/).
Finally, we add a description of the new release process. Our README and CONTRIBUTING files don’t have a standard structure, so please check that we have updated a correct file and that the new section makes sense for this gem.
=> Switch to trusted publishing workflow and run it on version.rb changes

Gemfile.lock, lib/zendesk_apps_support/validations/manifest.rb, lib/zendesk_apps_support/version.rb, spec/validations/manifest_spec.rb
💐
The warning regarding password parameter deprecation was mistakenly being added on every single validation.
This change updates the logic to only show the warning if a parameter of type 'password' is present in the manifest.
[APPS-7218](https://zendesk.atlassian.net/browse/APPS-7218)
* [low] Password parameter warning is not added appropriately.
* [low] Issues with validation flow.
=> [APPS-7218] Show password parameter warning conditionally

lib/zendesk_apps_support/app_requirement.rb, lib/zendesk_apps_support/validations/custom_objects_v2/schema_validator.rb, spec/validations/custom_objects_v2/custom_objects_v2_spec.rb, spec/validations/custom_objects_v2/limits_validator_spec.rb, spec/validations/custom_objects_v2/schema_validator_spec.rb
💐
The PR includes changes related to addition of unique `key` in triggers schema. It also includes addition of new constants.
New schema would look like this:
```
{
"custom_objects_v2": {
"objects": [{......}],
"object_fields": [{.....}],
"object_triggers": [
{
"key": "welcome_trigger"
"title": "Welcome Trigger",
"object_key": "apartment",
"conditions": {
"all": [],
"any": [
{"field": "priority", "operator": "is", "value": "urgent"},
{"field": "type", "operator": "is", "value": "incident"}
]
},
"actions": [
{"field": "assignee_id", "value": "123456789"}
]
}
]
}
}
```
[Link to a JIRA or GitHub issue here if relevant](https://zendesk.atlassian.net/browse/CRYSTAL-498)
* [HIGH | medium | low] What features does …
=> [CRYSTAL-498]Add unique key in trigger schema

lib/zendesk_apps_support/package.rb, lib/zendesk_apps_support/validations/requirements.rb, spec/package_spec.rb, spec/validations/requirements_spec.rb
💐
The PR includes changes related to addition of flag to prevent validation of cov2 requirements when feature flag is disabled in ZAM.
- Extend Package#validate/validate! with custom_objects_v2_requirements parameter
- Update Requirements.call to conditionally validate COV2 based on opts flag
- Add thorough test coverage for both enabled/disabled validation scenarios
[Link to a JIRA or GitHub issue here if relevant](https://zendesk.atlassian.net/browse/CRYSTAL-514)
Yes, it is called during app zip validation
* [HIGH | medium | low] What features does this touch?
Low: This change is called during zip validation
=> [CRYSTAL-514] Add a flag for the gating validation of cov2 requirements

config/locales/en.yml, lib/zendesk_apps_support/app_requirement.rb
💐
The PR includes changes related to Updating the en.yml using the i18n rake task to contain all the cov2 error messages translations. This change is needed so that ZAM UI won’t show these error messages as translations missing.
JIRA: https://zendesk.atlassian.net/browse/CRYSTAL-144
* [RUNTIME] No
* [low] Only adding the missing cov2 translations in en.yml
=> [CRYSTAL-144] Add Custom Objects V2 validation error messages in en.yml
