zendesk/zendesk_apps_support

lib/zendesk_apps_support/validations/source.rb

Allow moment

---

Gemfile
Gemfile.lock
lib/zendesk_apps_support/app_version.rb
lib/zendesk_apps_support/validations/manifest.rb
lib/zendesk_apps_support/validations/requirements.rb
lib/zendesk_apps_support/validations/translations.rb
lib/zendesk_apps_support/validations/validation_error.rb
spec/validations/manifest_spec.rb
spec/validations/validation_serialization_spec.rb
zendesk_apps_support.gemspec

Swap out MultiJson in favor of JSON

---

lib/zendesk_apps_support/assets/default_template.html.erb
spec/app/templates/layout.hdbs
spec/app_nomanifest/templates/layout.hdbs
spec/invalid_app/templates/layout.hdbs
spec/package_spec.rb

Proper html5

---

lib/zendesk_apps_support/validations/manifest.rb

:koala: 
Add organization_sidebar to locations
Relates to:
* Console - zendesk/zendesk_console#8401
* ZAF - zendesk/zendesk_app_framework#425
- Jira link: https://zendesk.atlassian.net/browse/AF-30
- None

[AF-30] Add apps in organization sidebar 

---

Gemfile.lock
zendesk_apps_support.gemspec

:koala:
This gem gets updated every couple of years or so:
https://github.com/jshint/jshint/compare/d459a40914a26c566ba82bb145e97573ff123879...bfcc86d6e51f53ae1e05cfdd33618e9bc0a9a957
- Jira link: 
- None

bump jshintrb

---

lib/zendesk_apps_support/package.rb
spec/package_spec.rb

:koala:
copied function from ZAM to check for noTemplates array
Describe your PR
- Jira link: 
- None

copied function from ZAM to check for noTemplates array

---

Gemfile.lock
config/locales/en.yml
lib/zendesk_apps_support/validations/manifest.rb
spec/validations/manifest_spec.rb

:koala:
- Jira link: https://zendesk.atlassian.net/browse/ZA-17
- App locations may not validate correctly

[ZA-17] Add support for multi-host apps

---

config/locales/translations/zendesk_apps_support.yml

@mariasica @ydrain @craig-day 
low.  English edits and title improvements.

HD-612 Strings: reverse sweep

---

.travis.yml
lib/zendesk_apps_support/validations/source.rb

:koala:
Things that JSHint will allow after this PR:
https://github.com/stereobooster/jshintrb/blob/v0.3.0/lib/js/jshint.js#L6189-L6509

allow plenty more constants

---

lib/zendesk_apps_support/package.rb
lib/zendesk_apps_support/validations/source.rb
spec/validations/source_spec.rb

:koala:
app.js was being included in the modules because the tests appended app.js to package.@lib_files which was terrible, so I fixed it.
- Jira link: 
- None

Double app.js fix

---

lib/zendesk_apps_support/package.rb

:v:
Only look at js files named app.js or in the lib folder.
* None

Only look at js files named app.js or in the lib folder

---

spec/invalid_app/lib/invalid.js
spec/validations/source_spec.rb

:v:
more jshint errors in the invalid app so it's easier to compare if we switch to eslint
* JIRA: 
* None

More jshint tests

---

lib/zendesk_apps_support.rb
lib/zendesk_apps_support/location.rb
lib/zendesk_apps_support/validations/manifest.rb

:koala:
to replace our Location model in ZAM
- Apps with valid locations may fail validation
- Apps with invalid locations may validate successfully

[AF-224] Add Location

---

lib/zendesk_apps_support/location.rb
lib/zendesk_apps_support/validations/manifest.rb

:koala:
http://blog.vrinek.io/2015/01/15/ruby-2-2/
- None

Fix circular reference warning

---

lib/zendesk_apps_support/location.rb

:v:
Add an orderable attribute to the locations. IMO this is a great candidate for replacement with a [Struct](http://ruby-doc.org/core-2.3.0/Struct.html) but they are a bit less flexible and people are less familiar with them.
* JIRA: https://zendesk.atlassian.net/browse/AF-238
* malformed installed.js (apps don't load)
* breaks reordering

AF-238 orderable attribute

---

lib/zendesk_apps_support/package.rb
spec/fixtures/legacy_app_no_template.js
spec/package_spec.rb

:v:
Fix for setting no_template to false instead of the array it should be.
* JIRA: https://zendesk.atlassian.net/browse/AF-248
* Templates are not shown correctly.

[AF-248] Fix for setting no_template

---

lib/zendesk_apps_support/assets/installed.js.erb

This will not fix the root cause of the current RA but should limit the breakage to the bad app.
@gardhauge

Only try to install if the app exists

---

lib/zendesk_apps_support/product.rb

:bear:
Add info on Zendesk products
* JIRA: https://zendesk.atlassian.net/browse/APPS-2897
* None

[APPS-2897] Add Zendesk products

---

lib/zendesk_apps_support/product.rb

:bear:
Change product id to product code to match DB schema. https://github.com/zendesk/zendesk_database_migrations/pull/475
* JIRA: https://zendesk.atlassian.net/browse/APPS-2897
* None

[APPS-2897] Change product id to product code

---

lib/zendesk_apps_support.rb

:bear:
Autoload `Product`
* JIRA: https://zendesk.atlassian.net/browse/APPS-2897
* None

[APPS-2897] Autoload product

---

lib/zendesk_apps_support/product.rb

:bear:
Change `zopim` to `chat`, as suggested by @timbertson https://github.com/zendesk/zendesk_app_market/pull/1720#discussion_r61212533
* None

Change zopim to chat

---

README.md

readme according to standards

---

lib/zendesk_apps_support/package.rb
spec/package_spec.rb

@zendesk/vegemite @zendesk/wombat

AF-346 dont treat no-location apps as framework v2

---

lib/zendesk_apps_support.rb
lib/zendesk_apps_support/finders.rb
lib/zendesk_apps_support/location.rb
lib/zendesk_apps_support/package.rb
lib/zendesk_apps_support/product.rb
lib/zendesk_apps_support/validations/manifest.rb
spec/fixtures/iframe_app.js
spec/fixtures/legacy_app_en.js
spec/fixtures/legacy_app_nl.js
spec/fixtures/legacy_app_no_template.js

:v:
**needed for the `signedUrls` manifest parameter to be exposed to the framework**
Add signedUrls parameter to appClass
* JIRA: https://zendesk.atlassian.net/browse/AF-231
* None, defaults to false (opt-in parameter)

Add signedUrls parameter to appClass

---

lib/zendesk_apps_support/location.rb

:bear:
Make chat_sidebar orderable.
* JIRA: https://zendesk.atlassian.net/browse/APPS-2981
* [low] break zopim apps reordering

[APPS-2981] make chat_sidebar orderable

---

config/locales/en.yml
config/locales/translations/zendesk_apps_support.yml
lib/zendesk_apps_support/validations/manifest.rb

:v:
Error when using iframe apps and framework version < 2.0
* JIRA:

[AF-371] framworkVersion < 2.0 error

---

Gemfile.lock

:v:
Updated all the gems, because I was getting deprecated warnings.
* JIRA: 
- ZAM or ZAT or ZAS stops working because dependency changed.

Gem update

---

config/locales/en.yml
config/locales/translations/zendesk_apps_support.yml
lib/zendesk_apps_support/manifest.rb
lib/zendesk_apps_support/validations/manifest.rb
spec/validations/manifest_spec.rb

populate used hosts

---

lib/zendesk_apps_support/validations/marketplace.rb
spec/validations/marketplace_spec.rb

whitelists the hashParams experiment
cc @zendesk/vegemite

whitelist and test hashParams experiment

---

lib/zendesk_apps_support/location.rb
lib/zendesk_apps_support/package.rb
lib/zendesk_apps_support/product.rb

:v:
Allow lotus box as a location in the form of 'standalone_chat'
* JIRA: https://zendesk.atlassian.net/browse/AF-486

[AF-486] standalone_chat location

---

lib/zendesk_apps_support/manifest.rb

:v:
Make name a thing
* JIRA: 
- [high] roman unpleased

Add name to manifest

---

lib/zendesk_apps_support/package.rb

:v:
Allow ticket_editor apps to have svgs
* JIRA:

ticket editor app svg

---

config/locales/translations/zendesk_apps_support.yml

/cc @zendesk/i18n
Low. English edits and title improvements.

[LOCAL-44] Strings: reverse sweep (auto)

---

config/locales/en.yml
config/locales/translations/zendesk_apps_support.yml
lib/zendesk_apps_support/location.rb
lib/zendesk_apps_support/manifest.rb
lib/zendesk_apps_support/validations/manifest.rb
spec/validations/manifest_spec.rb

:v:
Adds validation for v2 only locations in v1 apps
* JIRA: https://zendesk.atlassian.net/browse/AF-572

[AF-572] Implement validation to prevent the creation of v1 apps targeting v2 only locations

---

lib/zendesk_apps_support/package.rb

make some stuff public and cache app_js

---

lib/zendesk_apps_support/validations/validation_error.rb

@zendesk/vegemite @zendesk/wombat 
Fixes ruby code responsible for duplicate keys

Fix cheeky ruby code. Duplicate objects

---

lib/zendesk_apps_support/location.rb

:v:
Adds a `collapsible` flag to the app location properties. For consumption in AF-910 (will link)
* JIRA: https://zendesk.atlassian.net/browse/AF-910
* None/Low - causes issues in consumers utilising all of the properties of the `Location` class

[AF-910] Add 'collapsible' to app location properties

---

lib/zendesk_apps_support/app_version.rb
lib/zendesk_apps_support/validations/manifest.rb
spec/app_version_spec.rb

:bear:
@zendesk/vegemite 
@jayvee 
🛑 DO NOT MERGE UNTIL MARCH 1st
Deprecate v1 apps.
Screenshot for the removed warning that no longer makes sense
* JIRA: https://zendesk.atlassian.net/browse/APPS-3372
* Low - Breaks apps validation

[APPS-3372] Deprecate v1 apps

---

config/locales/en.yml
config/locales/translations/zendesk_apps_support.yml
lib/zendesk_apps_support/validations/manifest.rb
spec/validations/manifest_spec.rb

Fixed the error message. Also passed the path param!

fix error message

---

Gemfile.lock
lib/zendesk_apps_support/installation.rb

@zendesk/wombat 
adds support to plan. To be used in ZAM in order to expose plan information to the framework

[APPS-4597] Add plan support to installation

---

config/locales/en.yml
config/locales/translations/zendesk_apps_support.yml

🐕 
/cc @zendesk/dingo @zendesk/localization 
Strings for https://github.com/zendesk/zendesk_apps_support/pull/226.
<a href="https://cl.ly/37cea0ef143c" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/2B0l3w2k3L3r1X1q2S2L/Image%202019-05-16%20at%204.19.33%20pm.png" style="display: block;height: auto;width: 100%;"/></a>
* JIRA: https://zendesk.atlassian.net/browse/MPORT-445

[MPORT-445] Add strings for secret warnings

---

config/locales/en.yml
config/locales/translations/zendesk_apps_support.yml

🐕 
/cc @zendesk/dingo @zendesk/localization 
Strings for https://github.com/zendesk/zendesk_apps_support/pull/230.
* JIRA: https://zendesk.atlassian.net/browse/MPORT-443

[MPORT-443] Add strings for insecure and block-listed request warnings/errors

---

Gemfile.lock
zendesk_apps_support.gemspec

This reverts commit 9a3ec0e17ef4bc4291450291b28e470b43fcf0c8.

Revert "v4.18.0"

---

lib/zendesk_apps_support/location.rb
lib/zendesk_apps_support/product.rb
spec/product_spec.rb

These locations will be used firstly by Sell app market. Sell-specific
apps will be able to determine in which Sell location they will appear
at.
This is part of Sell's App Framework project.

Adding Sell product and Sell-related locations.

---

Gemfile.lock
zendesk_apps_support.gemspec

cc: @zendesk/dingo @zendesk/wattle @zendesk/vegemite 
Bumping ZAS to version 4.21.0.
Want to make sure that this push builds successfully on travis.

Bump ZAS to v4.21.0

---

Gemfile.lock
lib/zendesk_apps_support/validations/requests.rb
spec/validations/requests_spec.rb

Fixes bug found in production
https://zendesk.atlassian.net/browse/MPORT-528

[MPORT-528] Ignores anything that is not an IP Address

---

lib/zendesk_apps_support/location.rb

/cc @zendesk/wombat @zendesk/vegemite
Adds a 'visible' attribute to locations. This attribute will be used to check if a location should be shown in app details on the installation page.
https://zendesk.atlassian.net/browse/APPS-4832

[APPS-4832] Add visible attribute to locations

---

config/locales/en.yml
config/locales/translations/zendesk_apps_support.yml

Just a rename to match the new term for custom objects, no other changes.

Add strings that refer to custom objects rather than resources

---

Gemfile.lock
zendesk_apps_support.gemspec

Brings in https://github.com/zendesk/zendesk_apps_support/pull/263

Bump version to v4.26.0

---

config/locales/en.yml
config/locales/translations/zendesk_apps_support.yml

@zendesk/wombat @zendesk/localization 
Added translations for when there are more than one oauth type parameters

[APPS-4892]Add translations

---

Gemfile.lock
zendesk_apps_support.gemspec

Version that adds the new `oauth` kind

bump version to 4.27.0

---

Gemfile.lock
zendesk_apps_support.gemspec

Includes https://github.com/zendesk/zendesk_apps_support/pull/267

[DINGO-722] Bump version to 4.29.0

---

Gemfile.lock
zendesk_apps_support.gemspec

Makes `location_icons` a public method.

Bump to v4.29.1

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
README.md

💐
Adds some housekeeping around gem contributions - a CODEOWNERS file, a PR template and some more up-to-date information in the README
* JIRA: https://zendesk.atlassian.net/browse/
* [RUNTIME] None
* None: doc only

Update README, add CODEOWNERS and PR template

---

Gemfile.lock
zendesk_apps_support.gemspec

🐕
Bump to 4.29.2 to bring in new Sell location
No - it's just a new location
Low: adds a new location

Bump to 4.29.2 to bring in new Sell location

---

Gemfile.lock
zendesk_apps_support.gemspec

Bumping Gem Version for Publishing
* Low risk

Bump Version in Gemspec for publishing

---

Gemfile.lock
zendesk_apps_support.gemspec

ZAS BUMP v4.29.4

---

Gemfile.lock
zendesk_apps_support.gemspec

🐕
Bump ZAS so that we have a shiny new version that we can use in things like ZAT.
* Low.  Might lead to regressions with ZAT and other systems of which this is a dependency

[VEGEMITE-312] bump zas

---

README.md

🐕
/cc @zendesk/dingo @zendesk/vegemite
Update README.md outdated information related to bundler gem version
* [low] only updated README

Update README.md outdated information related to bundler gem version

---

README.md
lib/zendesk_apps_support/app_requirement.rb

🐕
/cc @zendesk/dingo @zendesk/vegemite
Add a new requirement type: `webhooks`
JIRA: https://zendesk.atlassian.net/browse/DINGO-1531
* [low] Added a string at the end of the TYPE array

[DINGO-1531] Add a new requirement type: `webhooks`

---

Gemfile.lock
zendesk_apps_support.gemspec

🐕
Create new release to 4.30.0
JIRA: https://zendesk.atlassian.net/browse/DINGO-1531
* [ low] Update version

[DINGO-1531] v4.30.0

---

Gemfile.lock
zendesk_apps_support.gemspec

🐕
Bumps version to include this change: https://github.com/zendesk/zendesk_apps_support/commit/ab7c01b0b4112e7aae9dbdb144c7d2d683d41548
* [low] Incorrectly bumps version

[DINGO-1662]  Bump version to v4.30.1

---

Gemfile.lock
lib/zendesk_apps_support/validations/requirements.rb
spec/validations/requirements_spec.rb
zendesk_apps_support.gemspec

🐕
https://zendesk.atlassian.net/browse/DINGO-1663
low, fails validation if app has http target requirements

[DINGO-1663] Disable creating http targets

---

Gemfile.lock
zendesk_apps_support.gemspec

🐕
/cc @zendesk/dingo @zendesk/wattle 
Minor version bump
https://zendesk.atlassian.net/browse/APPS-5783

Update minor version

---

spec/validations/manifest_spec.rb

🐕
Add more tests and improve existing tests
https://zendesk.atlassian.net/browse/DINGO-1723
* [low] fixing test only

[DINGO-1723] Add more tests

---

Gemfile.lock
zendesk_apps_support.gemspec

🐕
Bump version to v4.34.1
[Link to a JIRA or GitHub issue here if relevant](https://zendesk.atlassian.net/browse/DINGO-1723)
* [low] test changes only

[DINGO-1723] Bump version to v4.34.1

---

Gemfile.lock
zendesk_apps_support.gemspec

🐕
Bump version to v4.35.0
https://zendesk.atlassian.net/browse/DINGO-1836
* [low] Adding extra field

[DINGO-1836] bump to v4.35.0

---

Gemfile.lock
zendesk_apps_support.gemspec

🐕
Bump version to v4.35.1
https://zendesk.slack.com/archives/C2BAXN0JH/p1658113415923469
* [low] adding new workflow

bump to v4.35.1

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
README.md

🐕
Remove dingo references
https://zendesk.atlassian.net/browse/APPS-6367
* [RUNTIME] No
* [low] doc changes

[APPS-6367]Update code owners

---

Gemfile.lock
zendesk_apps_support.gemspec

💐
Bump to 4.36.0
https://zendesk.atlassian.net/browse/APPS-6388
* [HIGH | medium | low] What features does this touch?

[APPS-6388] Bump to v4.36.0

---

Gemfile.lock
zendesk_apps_support.gemspec

💐
Bump version to v4.37.0.
Changes included in new version: https://github.com/zendesk/zendesk_apps_support/pull/343
https://zendesk.atlassian.net/browse/APPS-6222
* [low] Breaks apps validation

Bump version to v4.37.0

---

Gemfile.lock
zendesk_apps_support.gemspec

💐
Bump version to v4.38.0.
Changes included in new version: https://github.com/zendesk/zendesk_apps_support/pull/345
[Link to a JIRA or GitHub issue here if relevant](https://zendesk.atlassian.net/browse/APPS-6494)
* [low] What features does this touch? Remove deprecated framework versions

[APPS-6494] Bump version to v4.38.0

---

Gemfile.lock
zendesk_apps_support.gemspec

💐
Bump version to 4.38.1.
Changes included in new version: 
- https://github.com/zendesk/zendesk_apps_support/pull/348
- https://github.com/zendesk/zendesk_apps_support/pull/349
* [RUNTIME] Can this change affect apps rendering for a user? Unlikely
* [low] What features does this touch? Gems upgrade

Bump version to 4.38.1

---

Gemfile.lock
zendesk_apps_support.gemspec

💐
Bumping version in preparation for a new release
* [RUNTIME] No. Just a version bump.
* [low] No feature change.

Bump version to v4.40.0

---

Gemfile.lock
zendesk_apps_support.gemspec

💐
bump version 4.41.0
Risks
[RUNTIME] No. Just a version bump.
[low] No feature change.

bump version 4.41.0

---

.github/CODEOWNERS
README.md

💐
Wattle is taking full ownership of this project. Removing Vegemite references.
* [RUNTIME] No
* [low] Just doc changes.

Remove Vegemite references

---

config/locales/translations/zendesk_apps_support.yml

NOTE: String Sweep will be suspended for this repo until this PR is merged or closed!
fyi @zendesk/i18n ???
No
None. English edits and title improvements.

Strings: Reverse Sweep (auto)

---

Gemfile.lock
zendesk_apps_support.gemspec

💐
Bump version to 4.42.0
* [low] version bump

Bump version to 4.42.0

---

config/locales/translations/zendesk_apps_support.yml

💐
The PR implements translation changes. These are translations for all the validation errors raised due to violation of `custom_objects_v2` product limits.
[Jira](https://zendesk.atlassian.net/browse/CRYSTAL-380)
[RFC](https://docs.google.com/document/d/1160POHo000wZgUSqv18TX4AhXX_15MkHmnwEf0qLfMI/edit?tab=t.xpv08zctki8y#heading=h.kobkbh74kfxk)
* [Low] What features does this touch?
This PR contains only translations which are not yet consumed anywhere

[CRYSTAL-380]Add validation errors translations for cov2 product limit violations

---

config/locales/translations/zendesk_apps_support.yml

💐
The PR changes includes new translations for cov2 validations
https://zendesk.atlassian.net/browse/CRYSTAL-380
* [HIGH | medium | low] What features does this touch?

Add new translations for cov2 validations
